id: I1184C44B
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T08:57:20.267861'
last_modified: '2022-06-19T08:57:20.267874'
parser: null
source_metadata:
  title: Autobiography of Sa skya bdag chen Kun dga blo gros (1729–1783); Lamdre Lobshe,
    vol. cha, title no. 2
  author: བདག་ཆེན་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-04);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/577
  bases:
    c6f6:
      title: Autobiography of Sa skya bdag chen Kun dga blo gros (1729–1783); Lamdre
        Lobshe, vol. cha, title no. 2
      order: 1
      base_file: c6f6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
